### ISSUE TITLE
Installing and configuring different versions of R.

### ISSUE THREAD

**Issue by grabear** [datasnakes/rinse#2]
_From @grabear on May 8, 2018 3:49_

https://cran.r-project.org/doc/manuals/r-release/R-admin.html#Installation

_Copied from original issue: datasnakes/beRi#13_

**Comment by grabear** [comment]
I just found this on GitHub.  @sdhutchins 
https://github.com/spack/spack/blob/develop/var/spack/repos/builtin/packages/r/package.py

**Comment by sdhutchins** [comment]
Nice! I starred this earlier and I never even considered how it could be used for this package. Glad you posted that here. My initial thought was using it for our server :pensive: or on the MCSR. 

Related, check out www.numfocus.org.

I was writing up an email (I had to leave :cry:) about the grants that NumFocua funds. They seem to be pretty open proposals and I think the nature of beri would be perfect for it (it's built in python and helps tackle data science). I saw spack and some other cool stuff on their site.

**Comment by sdhutchins** [comment]
A bit more about spack...

To install R, it's as simple as the below...

```console
spack install r@3.5.2
```

The installation location can be edited as well...(https://spack.readthedocs.io/en/latest/config_yaml.html?highlight=install%20location) in spack's `config.yaml`


```yaml
config:
  # This is the path to the root of the Spack install tree.
  # You can use $spack here to refer to the root of the spack instance.
  install_tree: $spack/opt/spack


  # Locations where templates should be found
  template_dirs:
    - $spack/share/spack/templates


  # Default directory layout
  install_path_scheme: "${ARCHITECTURE}/${COMPILERNAME}-${COMPILERVER}/${PACKAGE}-${VERSION}-${HASH}"


  # Locations where different types of modules should be installed.
  module_roots:
    tcl:    $spack/share/spack/modules
    lmod:   $spack/share/spack/lmod
    dotkit: $spack/share/spack/dotkit
```

Ultimately, we need to test out spack on a server to get a better feel for it. 

- [ ] Using spack's api to create a thin wrapper around their R installation script.
- [ ] Decide if there are additional R packages we want to include in the base R installation.
